baseURL = "https://wallhalle.circum.space/"
title = "wallhalle"
languageCode = "en"
disableKinds = ["taxonomy", "term", "rss", "sitemap"]
enableRobotsTXT = true

[params]
  tagline = "Paintings of the sublime, sized for large screens"

[params.donate]
  bitcoin = "bc1qjt5n267ka8zuagtmrurez9vjs43hlg3qkqc8sc"
  bitcoin_sp = ""
  monero = "8AuPVyudY9hRedjkRzCisrDq5rnzbUvCTckcQr5dUaGWa1yzo77uMUP8LPpSQvPBbGEktHpPqkHFPdXuCYBEL6iz9kXAhFW"
  lightning = "hermeticvm@minibits.cash"

[markup.goldmark.renderer]
  unsafe = false

[minify]
  minifyOutput = true
