baseURL = "http://localhost:1313/"
title = "wallpaintr"
languageCode = "en"
disableKinds = ["taxonomy", "term", "rss", "sitemap"]
enableRobotsTXT = true

[outputs]
  home = ["HTML", "index", "list6k169", "list5k169", "list5k1610", "list4k169"]

[mediaTypes."text/plain"]
  suffixes = ["txt"]

[outputFormats.index]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[outputFormats.list6k169]
  mediaType = "text/plain"
  baseName = "6k-16x9"
  path = "lists"
  isPlainText = true

[outputFormats.list5k169]
  mediaType = "text/plain"
  baseName = "5k-16x9"
  path = "lists"
  isPlainText = true

[outputFormats.list5k1610]
  mediaType = "text/plain"
  baseName = "5k-16x10"
  path = "lists"
  isPlainText = true

[outputFormats.list4k169]
  mediaType = "text/plain"
  baseName = "4k-16x9"
  path = "lists"
  isPlainText = true

[params]
  tagline = "Paintings of the sublime, sized for large screens"

[params.donate]
  bitcoin = "bc1qjt5n267ka8zuagtmrurez9vjs43hlg3qkqc8sc"
  bitcoin_sp = ""
  monero = "8AuPVyudY9hRedjkRzCisrDq5rnzbUvCTckcQr5dUaGWa1yzo77uMUP8LPpSQvPBbGEktHpPqkHFPdXuCYBEL6iz9kXAhFW"
  lightning = "hermeticvm@minibits.cash"

[markup.goldmark.renderer]
  unsafe = false

[minify]
  minifyOutput = true
